version: 0.0  # codeDeploy의 버전, 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류발생
os: linux
files:     # s3에 업로드 된 파일이 ec2의 어느곳으로 이동시킬지 지정
  - source: /    # s3의 루트 디렉토리를 나타냄. 루트경로(/)는 s3에서 받은 모든파일 의미, destination으로 이동시킬 대상을 지정
    destination: /home/ec2-user/app/step2/zip/   # ec2 디렉토리. source에서 ec2로 지정된 파일을 받을 위치
    overwrite: yes  # 기존에 파일들이 있으면 덮어쓸지

permissions:    # codeDeploy에서 ec2서버로 넘겨준 파일들을 모두 ec2-user권한을 갖도록 함
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:      # CodeDeploy 배포 단계에서 실행할 명령어를 지정합니다.
  ApplicationStart:     # ApplicationStart라는 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 합니다.
    - location: deploy.sh
      timeout: 60       # 60으로 스크립트 실행 60초 이상 수행되면 실패가 됩니다(무한정 기다릴 수 없으니 시간 제한을 둬야만 합니다).
      runas: ec2-user